name: Test GitHubToken Excessive Permissions

on:
  push:
    branches:
      - main

jobs:
  test-permissions:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dummy Step
        run: echo "This is to test excessive token permissions"
