name: "Semgrep Scan on Push"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep Scan
        run: |
          semgrep --config .github/workflows/semgrep-rule.yml --json > semgrep-results.json

      - name: Upload Semgrep Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.json
