name: Test GitHubToken Excessive Permissions
on:
  push:
    branches:
      - main
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  test-permissions:
    runs-on: ubuntu-latest
    # Overly broad permissions for GITHUB_TOKEN
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
      checks: write
      deployments: write
      statuses: write
      packages: write
      repository-projects: write
      discussions: write
      security-events: write  # This one, in particular, should raise a flag as it's typically not needed for most workflows
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Dummy Step
        run: echo "This is to test excessive token permissions"