# This is a SAMPLE GitHub Actions workflow
# Click on the "Secure Workflow" button to automatically secure it

name: Node.js Package
on:
  push:
    branches:
      - main
    
permissions:  # added using https://github.com/step-security/secure-repo
  contents: write
  issues: write
  pull-requests: write
  actions: write
  checks: write
  deployments: write
  statuses: write
  packages: write
  repository-projects: write
  discussions: write
  security-events: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest  
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout2@v2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}