# This is a SAMPLE GitHub Actions workflow
# Click on the "Secure Workflow" button to automatically secure it

name: Node.js Package
on:
  release:
    types: [created]
    
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout2@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}